import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./styles/globals.scss";
import StoreProvider from "./storeProvider";
import IconsSprite from "../components/icons/IconsSprite";
import Popup from "../components/popup/Popup";
import Notification from "@/ui/notification/Notification";
import InitData from "@/components/InitData";
import Header from "./_header/HeaderLayout";
import Footer from "./_footer/FooterLayout";
import { Suspense } from "react";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});
const spaceGrotesk = Space_Grotesk({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
});

export default async function RootLayout(
	props: Readonly<{
		children: React.ReactNode;
	}>,
) {
	const { children } = props;

	return (
		<StoreProvider>
			<html
				lang="en"
				className={`${inter.className} ${spaceGrotesk.className}`}
			>
				{/* <head>
					<link
						rel="preconnect"
						href="https://fonts.googleapis.com"
					></link>
					<link
						rel="preconnect"
						href="https://fonts.gstatic.com"
						// crossOrigin="anonymous"
					></link>
					<link
						href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,700;1,14..32,700&display=swap"
						rel="stylesheet"
					></link>
					<link
						href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,700;1,14..32,700&family=Space+Grotesk:wght@300..700&display=swap"
						rel="stylesheet"
					></link>
				</head> */}
				<body id="body">
					<div id="root">
						<div id="popup"></div>
						<div id="overlay"></div>
						<div id="notification-container"></div>
						<Header />
						{children}
						<Footer />
					</div>
					<Popup />
					<Notification />
					<IconsSprite />
					<InitData />
				</body>
			</html>
		</StoreProvider>
	);
}
