import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import NavigationBar from "./components/elemets/navigation/navigationBar";
import StoreProvider from "./storeProvider";
import IconsSprite from "./components/icons/IconsSprite";
import Footer from "./components/elemets/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <div id="root">
            <div id="popup"></div>
            <div id="overlay"></div>
            <nav>
              <NavigationBar />
            </nav>
            <main>{children}</main>
            <footer>
              <Footer />
            </footer>
          </div>
          <IconsSprite />
        </body>
      </html>
    </StoreProvider>
  );
}
