version: "3.5"
services:
    user-microservice:
        container_name: user-microservice
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            DATABASE_URL: postgresql://${POSTGRES_DB_USER}:${POSTGRES_DB_PASSWORD}@${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}?schema=user
            DIRECT_DATABASE_URL: postgresql://${POSTGRES_DB_USER}:${POSTGRES_DB_PASSWORD}@${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}?schema=user
        env_file:
            - ./.env
        ports:
            - "11000:11000"
        networks:
            - user
            - docker_nayzak

networks:
    user:
        driver: bridge
    docker_nayzak:
        external: true
